apiVersion: core.database-mesh.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: nginx-deployment
  namespace: injecttest
  annotations:
    "database-mesh.io/metrics-port": "8888"
spec:
  services:
    - name: "my_mysql"
      databaseMySQL:
        host: "localhost"
        port: 3306
        user: "root"
        password: "root"
        db: "foo"
        poolSize: 3
      trafficStrategy: "trafficstrategy-sample"

---
apiVersion: core.database-mesh.io/v1alpha1
kind: TrafficStrategy
metadata:
  name: trafficstrategy-sample
  namespace: injecttest
spec:
  selector:
    matchLabels:
      source: rds
  loadBalance:
    simpleLoadBalance:
      kind: "random"
  circuitBreaks:
    - regex: "/[1-9][0-9]*/"
    - regex: "/[1-2][0-9]*/"
  concurrencyControls:
    - regex: "/[1-2][0-9]*/"
      duration: 1
      maxConcurrency: 11
    - regex: "/[1-7][0-9]*/"
      duration: 1
      maxConcurrency: 20

---
apiVersion: core.database-mesh.io/v1alpha1
kind: DatabaseEndpoint
metadata:
  name: databaseendpoint-sample1
  namespace: injecttest
  labels:
    source: rds
spec:
  database:
    MySQL:
      host: "127.0.0.1"
      port: 3306
      user: "root"
      password: "root"
      db: "foo"
---
apiVersion: core.database-mesh.io/v1alpha1
kind: DatabaseEndpoint
metadata:
  name: databaseendpoint-sample2
  namespace: injecttest
  labels:
    source: rds
spec:
  database:
    MySQL:
      host: "127.0.0.2"
      port: 3306
      user: "root"
      password: "root"
      db: "foo"
