apiVersion: v1
kind: Namespace
metadata:
  name: injecttest
  labels:
    pisanix.io/inject: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: injecttest
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        pisanix.io/inject: enabled
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80