[package]
name = "pisa-daemon"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pisa-daemon"
path = "src/main.rs"

[dependencies]
config = { path = "../app/config" }
traffic_qos = { path = "../app/traffic_qos" }