# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: core.database-mesh.io/v1alpha1
kind: DataShard
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"core.database-mesh.io/v1alpha1","kind":"DataShard","metadata":{"annotations":{},"labels":{"source":"test"},"name":"test","namespace":"default"},"spec":{"rules":[{"actualDatanodes":{"valueSource":{"nodes":[{"value":"ds001"},{"value":"ds002"}]}},"databaseStrategy":{"databaseShardingAlgorithmName":"mod","databaseShardingColumn":"id"},"tableName":"t_order"}]}}
  creationTimestamp: "2022-11-07T06:15:06Z"
  generation: 1
  labels:
    source: test
  name: test
  namespace: default
  resourceVersion: "102165794"
  uid: 8618a0c6-a781-41e1-822b-6e2445deb140
spec:
  rules:
  - actualDatanodes:
      valueSource:
        nodes:
        - value: ds001
        - value: ds002
    databaseStrategy:
      databaseShardingAlgorithmName: mod
      databaseShardingColumn: id
    tableName: t_order
