# api 配置块，对应命令行参数和环境变量
[admin]
# api 端口
port = "8081"
# 日志级别
log_level = "INFO"

# pisa-proxy 代理配置块
[proxy]
# config a proxy
[[proxy.config]]
# proxy 代理地址
listen_addr = "0.0.0.0:9088"
# proxy 认证用户名
user = "root"
# proxy 认证密码
password = "12345678"
# proxy schema
db = "test"
# 配置后端数据源类型
backend_type = "mysql"
# proxy 与后端数据库建连连接池大小，值范围：1 ~ 255, 默认值：64
pool_size = 3

# 后端负载均衡配置
[proxy.config.simple_loadbalance]
# 负载均衡算法：[random/roundrobin], 默认值: random 算法
balance_type = "random"
# 选择挂载后端节点
nodes = ["ds001"]

[[proxy.config.plugin.concurrency_control]]
regex = "aaa"
max_concurrency = 5
duration = 333

[[proxy.config.plugin.concurrency_control]]
regex = "bbb"
max_concurrency = 5
duration = 333

[[proxy.config.plugin.circuit_break]]
regex = "111"

[[proxy.config.plugin.circuit_break]]
regex = "222"

# 后端数据源配置
[mysql]
[[mysql.node]]
# 数据源 name
name = "ds001"
# database name
db = "kubestar_test"
# 数据库 user
user = "root"
# 数据库 password
password = "12345678"
# 数据库地址
host = "127.0.0.1"
# 数据库端口
port = 3306
# 负载均衡节点权重
weight = 1
