apiVersion: core.database-mesh.io/v1alpha1
kind: VirtualDatabase
metadata:
  name: nginx-deployment
  namespace: injecttest
  annotations:
    "database-mesh.io/metrics-port": "8888"
spec:
  services:
    - name: my_mysql
      databaseMySQL:
        host: localhost #默认是localhost
        port: "3306" #用户可以自己填，非空转为生成
        username: root #用户可以自己填，非空转为生成
        password: "12345678" #用户可以自己填，非空转为生成
        db: foo #用户可以自己填，或非空需要特殊处理
        poolSize: 3 #走默认值，先放在这里 int
      trafficStrategy: "trafficstrategy-sample"

---
apiVersion: core.database-mesh.io/v1alpha1
kind: TrafficStrategy
metadata:
  name: trafficstrategy-sample
  namespace: injecttest
spec:
  selector: #必选 kubernetes labels 格式
    matchLabels:
      source: rds
  loadBalance: #可选
    simpleLoadBalancer:
      kind: random
  circuitBreaks:
    - regex: "/[1-9][0-9]*/"
    - regex: "/[1-2][0-9]*/"
  ConcurrencyControls:
    - regex: "/[1-2][0-9]*/"
      duration: 1
      maxConcurrency: 11
    - regex: "/[1-7][0-9]*/"
      duration: 1
      maxConcurrency: 20

---
apiVersion: core.database-mesh.io/v1alpha1
kind: DatabaseEndpoint
metadata:
  name: databaseendpoint1
  namespace: injecttest
  labels:
    source: rds
spec:
  database:
    MySQL:
      host: "127.0.0.1"
      port: "3306"
      username: "root"
      password: "12345678"
      db: "foo"
---
apiVersion: core.database-mesh.io/v1alpha1
kind: DatabaseEndpoint
metadata:
  name: databaseendpoint2
  namespace: injecttest
  labels:
    source: rds
spec:
  database:
    MySQL:
      host: "127.0.0.2"
      port: "3306"
      username: "root"
      password: "12345678"
      db: "foo"
