apiVersion: v1
kind: Service
metadata:
  name: pisa-controller
spec:
  ports:
    - port: 443
      targetPort: 6443
      name: webhook
    - port: 8080
      targetPort: 8080
      name: config
  selector:
    app: pisa-controller