##
## Copyright 2022 SphereEx Authors
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "common.names.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "common.names.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "common.names.fullname" . }}
    spec:
      serviceAccountName: {{ template "common.names.fullname" . }}
      containers:
        - name: controller
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -webhookTLSCertFile=/etc/webhook/certs/tls.crt
            - -webhookTLSKeyFile=/etc/webhook/certs/tls.key
            - -webhookPort={{ .Values.service.webhookPort }}
            - -corePort={{ .Values.service.corePort }}
            - -proxyConfigsPort={{ .Values.service.proxyConfigsPort }}
            - -kubeconfig=""
          env:
            - name: PISA_PROXY_IMAGE
              value: {{ printf "%s:%s" .Values.proxyImage.repository .Values.proxyImage.tag | quote}}
            - name: PISA_CONTROLLER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PISA_CONTROLLER_SERVICE
              value: {{ include "common.names.fullname" . | quote }}
          ports:
            - name: webhook
              containerPort: {{ .Values.service.webhookPort }}
            - name: core
              containerPort: {{ .Values.service.corePort }}
            - name: proxy-configs
              containerPort: {{ .Values.service.proxyConfigsPort }}
          resources:
          {{- toYaml .Values.resources | nindent 12}}
      imagePullSecrets:
      {{- toYaml .Values.image.imagePullSecrets | nindent 8}}