
[package]
name = "metrics"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runtime_mysql = { path = "../../runtime/mysql" }
prometheus = "0.13.3"
