##
## Copyright 2022 SphereEx Authors
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

name: "Code coverage"

on:
  pull_request

env:
  GO_VERSION: 1.18.3
  GO_CODE_DIR: pisa-controller

jobs:
  go_coverage:
    name: "Golang code coverage"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout codes"
        uses: actions/checkout@v2
      - name: "Setup go faster"
        uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: ${{env.GO_VERSION}}
      - name: "Run test"
        run: |
          cd ${{env.GO_CODE_DIR}}
          go test --count=1 -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./${{env.GO_CODE_DIR}}/coverage.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
