name: PisaController CICD
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Go build
    runs-on: ubuntu-latest
    steps:
      - name: "checkout go"
        uses: actions/checkout@master
      - name: "Setup Go Faster"
        uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: '1.18.1'
      - uses: actions/cache@v1
        with:
          path: ~/go/pkg
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: openssl
        run: mkdir -p pisa-controller/build/certs && cd pisa-controller/build/certs && openssl req -new -SHA256 -newkey rsa:2048 -nodes -keyout tls.key -out tls.csr -subj "/C=CN/ST=beijing/L=beijing/O=/OU=/" && openssl x509 -req -sha256 -days 365 -in tls.csr -signkey tls.key -out tls.crt
      - name: "build"
        run: cd pisa-controller && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w -s" -gcflags "-N -l"  -o bin/controller cmd/main.go
      - name: "Kaniko build"
        uses: aevea/action-kaniko@master
        with:
          image: pisanixio/controller
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: pisa-controller/hack/Dockerfile 
        
