##
## Copyright 2022 SphereEx Authors
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
## http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##

name: Integration Test

on:
  push:
    branches:
      - master
      - ci 
      - release-v*

jobs:
  run:
    name: Integration Test
    runs-on: ubuntu-latest 
    steps:
      - name: "checkout codes" 
        uses: actions/checkout@v3
      - name: "setup kind"
        uses: helm/kind-action@v1.2.0
      - name: "setup helm"
        uses: azure/setup-helm@v2.1
      - name: "setup kubectl" 
        uses: azure/setup-kubectl@v2.0
      - name: "declare github variables" 
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          if [[ $GITHUB_REF == refs/tags/* ]]; then
             echo "##[set-output name=tags;]$(echo ${GITHUB_REF#refs/tags/})"  
             echo "##[set-output name=imagetag;]$(echo ${GITHUB_REF#refs/tags/})"  
          else
             echo "##[set-output name=tags;]$(echo '')"
             echo "##[set-output name=imagetag;]$(echo '')"
          fi
          if [[ $GITHUB_REF == refs/heads/* ]]; then
             echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"  
             echo "##[set-output name=imagetag;]$(echo ${GITHUB_REF#refs/heads/})"  
          else
             echo "##[set-output name=branch;]$(echo '')"
             echo "##[set-output name=imagetag;]$(echo '')"
          fi
      - name: "Pisa-Controller kaniko build"
        uses: mlycore/action-kaniko@master
        with:
          image: pisanixio/controller
          username: ${{ secrets.DOCKERHUB_CI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CI_PASSWORD }}
          registry: ${{ secrets.DOCKERHUB_CI_HOST }}
          build_file: pisa-controller/hack/Dockerfile 
          tag_with_latest: true
          extra_args: --build-arg GIT_BRANCH=${{ steps.vars.outputs.branch }} --build-arg GIT_COMMIT=${{ steps.vars.outputs.sha_short }} --build-arg GIT_TAG=${{ steps.vars.outputs.tags }}
      - name: "Pisa-Proxy kaniko build"
        uses: mlycore/action-kaniko@master
        with:
          image: pisanixio/proxy
          username: ${{ secrets.DOCKERHUB_CI_USERNAME }}
          password: ${{ secrets.DOCKERHUB_CI_PASSWORD }}
          registry: ${{ secrets.DOCKERHUB_CI_HOST }}
          build_file: pisa-proxy/hack/Dockerfile
          tag_with_latest: true
          extra_args: --build-arg GIT_BRANCH=${{ steps.vars.outputs.branch }} --build-arg GIT_COMMIT=${{ steps.vars.outputs.sha_short }} --build-arg GIT_TAG=${{ steps.vars.outputs.tags }}
      - name: "install Pisa Controller"
        run: |
          export PISANIX_NAMESPACE="pisanix-system"
          kubectl create namespace ${PISANIX_NAMESPACE}
          kubectl label namespace default pisanix.io/inject=enabled
          kubectl get namespaces --show-labels
          cd charts/pisa-controller 
          helm dependency build
          cd ..
          helm install pisa-controller pisa-controller -n ${PISANIX_NAMESPACE} --set image.tag=v0.1.0,proxyImage.tag=v0.1.0
          kubectl get pod -n ${PISANIX_NAMESPACE}
          kubectl wait --timeout=60s --for=condition=ready --all pod -n ${PISANIX_NAMESPACE}
          kubectl get deployment pisa-controller -n ${PISANIX_NAMESPACE} -o yaml  
          cd ..
          cd test/kubernetes
          kubectl apply -f mysql.yml 
          kubectl apply -f virtualdatabase.yml 
          kubectl apply -f trafficstrategy.yml
          kubectl apply -f databaseendpoint.yml
          kubectl apply -f app.yml 
          sleep 3
          kubectl wait --timeout=60s --for=condition=ready --all pod
          kubectl get pod --show-labels
          kubectl get pod -o yaml 
          kubectl logs $(kubectl get pod | grep test | cut -d" " -f1) pisanix-proxy
          kubectl port-forward svc/test 3308:3306 &
          # kubectl port-forward pod/$(kubectl get pod | grep mysql | cut -d" " -f1) 3308:3306 &
          sleep 3
      - name: "prepare mysql" 
        uses: shogo82148/actions-setup-mysql@v1
        with:
         mysql-version: '5.7'
      - name: "run some test" 
        run: mysql -h127.0.0.1 -P3308 -uroot -proot -e 'SELECT UNIX_TIMESTAMP()'