name: PisaProxy CICD
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  build:
    name: Rust build
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repo"
        uses: actions/checkout@master
      - name: "manifest"
        run:  echo `git log | grep commit | head -1 | cut -d" " -f2` > manifest
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.PAT }}:x-oauth-basic@github.com/database-mesh/lrpar".insteadOf "ssh://git@github.com/database-mesh/lrpar.git" 
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --manifest-path pisa-proxy/Cargo.toml
      - name: "Kaniko build"
        uses: mlycore/action-kaniko@master
        with:
          image: pisanixio/proxy
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: pisa-proxy/hack/Dockerfile
          tag_with_latest: true
